window.PAPERS = [
  {id:'A05',stars:5,title:'野中郁次郎 Nonaka 1994：組織知識創造的動態理論',en:'A Dynamic Theory of Organizational Knowledge Creation',role:'核心理論',status:'已建研讀包',year:'1994',author:'Ikujiro Nonaka',method:'理論建構',verdict:'SECI 模型的原典，是整篇論文的理論骨架。',question:'組織如何讓個人的隱性知識與顯性知識持續轉化，進而創造新知識？',theory:'隱性／顯性知識、SECI、知識螺旋、組織知識創造條件。',findings:'提出社會化、外化、結合、內化四種知識轉化，並說明知識如何由個人擴展到群組與組織。',use:'第二章理論基礎；定義 SECI 與隱性知識外化。',limit:'經典理論文獻，需搭配後續實證與 AI 情境研究，不可單獨證明 AI 工具成效。',tags:['SECI','隱性知識','核心理論'],drive:'https://drive.google.com/drive/folders/1xneeyO7aVSGBivRX2tNnhtGZoI99awRv',files:[['原文 PDF','A05/A05原文_A_Dynamic_Theory_of_Organizational_Knowledge_Creation_Nonaka1994.pdf'],['中英對照','A05/A05野中知識創造_段落中英對照_螢光標示_20260620.pdf'],['研讀簡報','A05/A05野中知識創造_研讀簡報_20260620.pdf']]},
  {id:'A04',stars:4,title:'SECI 與 ChatGPT 高等教育',en:'SECI Model and ChatGPT in Higher Education',role:'理論橋接',status:'已建研讀包',year:'2025',author:'Urpi Barreto & Yasser Abarca',method:'實證研究',verdict:'把 SECI 原典接到生成式 AI 與高等教育，是理論走向研究場域的橋梁。',question:'ChatGPT 如何與 SECI 知識創造流程整合，支援高等教育的知識管理？',theory:'SECI、生成式 AI、高等教育知識管理。',findings:'ChatGPT 可協助外化隱性思維、結合既有資訊，並透過對話支持內化。',use:'第二章 AI × SECI 的核心支撐；串接 A05 與後續 AI 情境文獻。',limit:'引用具體效果時須回到原文頁碼與研究設計核對。',tags:['SECI','ChatGPT','高等教育'],drive:'https://drive.google.com/drive/folders/1dCBzEFhyt23i5iM5DTNp7okhERpGMSnh',files:[['原文 PDF','A04/A04原文_SECI_and_ChatGPT_in_higher_education.pdf'],['中英對照','A04/A04論文_逐句中英對照_20260617.pdf'],['研讀簡報','A04/A04論文研讀_簡報_20260617.pdf']]},
  {id:'A06',stars:3,title:'生成式 AI 教育 CoP：Mayo Clinic',en:'Generative AI Education: Building a Community of Practice at Mayo Clinic',role:'實務案例',status:'已建研讀包',year:'2026',author:'Schultz, Van Erp, Minter & Nelson',method:'觀點文／實務案例',verdict:'提供生成式 AI 共學社群的真實案例，但不能當成因果成效證據。',question:'機構如何用低行政負擔的實踐社群推動生成式 AI 教育？',theory:'實踐社群 CoP、社會性學習、SECI 的社會化與外化。',findings:'小型志願團隊、非正式運作、既有工具與持續回饋，是低負擔 CoP 的四個要素。',use:'研究背景與實務佐證；說明 AI 學習與知識分享的社群情境。',limit:'文章定位為觀點文，適合提供情境與概念，不宜作方法論主幹。',tags:['CoP','Mayo Clinic','實務案例'],drive:'https://drive.google.com/drive/folders/1OcoTnkQx-zId-JH0l0R0-LxuZjq1f4x0',files:[['原文 PDF','A06/A06原文_Generative_AI_Education_CoP_at_Mayo_Clinic.pdf'],['中英對照','A06/A06共學團實踐社群_段落中英對照_20260624.pdf'],['研讀簡報','A06/A06共學團實踐社群_研讀簡報_20260624.pdf']]},
  {id:'A08',stars:4,title:'AI 強化型能力轉移樞紐：產學知識共享',en:'AI-Enhanced Competency Transfer Hubs',role:'概念框架',status:'已建研讀包',year:'2026',author:'Arya, Saraf, Chichkanov, Papa & Romano',method:'概念性框架',verdict:'把 AI 視為知識轉移媒介，補足 SECI 在跨組織協作上的應用視角。',question:'AI 如何強化大學與產業之間的能力轉移與知識共享？',theory:'知識轉移、開放創新、三螺旋、TCM-ADO。',findings:'提出知識擷取、客製化轉移、專案調適與回饋優化四層架構。',use:'第二章知識轉移與 AI 中介機制；支撐外化、結合與內化的技術角色。',limit:'概念模型仍需要實證驗證；不可直接推論實際成效。',tags:['知識轉移','產學協作','概念模型'],drive:'https://drive.google.com/drive/folders/14HWGkbXbP8i3gWfaIVGejKevcm4q9t4m',files:[['原文 PDF','A08/A08原文_AI-Enhanced_Competency_Transfer_Hubs.pdf'],['中英對照','A08/A08_中英對照_螢光筆版v2.pdf'],['口語小抄','A08/A08_中英對照_完整口語小抄版.pdf'],['研讀簡報','A08/A08_簡報_路C版.pptx']]},
  {id:'A10',stars:4,title:'GenAI 知識管理實證：軟體開發實務',en:'Generative AI Meets Knowledge Management',role:'實證研究',status:'已建研讀包',year:'2025',author:'Kirchner et al.',method:'質化訪談／11 位開發者',verdict:'直接呈現工作者改問 AI、少問同事的知識行為轉變。',question:'生成式 AI 如何改變軟體開發者的知識尋找、分享與驗證行為？',theory:'TOE 框架、生成式 AI、知識管理。',findings:'效率提升伴隨驗證、過度依賴與隱私風險；罕見或特定問題仍不可靠。',use:'研究動機與現象基礎；與本研究的量化檢索成效形成方法互補。',limit:'便利抽樣 11 人，不能推論整體母體；主框架是 TOE，不是 SECI。',tags:['質化訪談','TOE','工作實務'],drive:'https://drive.google.com/drive/folders/1VmKRZg7sHqLjDz1x3W4BQjk2_d7ppZtn',files:[['原文 PDF','A10/A10原文_GenAI_Meets_KM_Kirchner2025.pdf'],['中英對照','A10/A10中英對照.pdf'],['研讀簡報','A10/A10研讀簡報.pdf']]},
  {id:'A11',stars:5,title:'AI 知識管理理論修訂：人工知識生成',en:'Artificial Knowledge Generation',role:'核心理論',status:'已建基本卡',year:'2025',author:'Cerchione, Liccardo & Passaro',method:'文獻計量／1,411 篇',verdict:'直接提出「機器維度」修訂知識生成模型，是 SECI × GenAI 的關鍵理論文獻。',question:'生成式 AI 如何改變知識管理與知識生成理論？',theory:'SECI、人工知識生成、機器維度。',findings:'提出機器維度與 GenAI 就緒性分類法，說明 AI 已成為知識生成流程的新參與者。',use:'第二章理論修訂與研究缺口；說明傳統 SECI 在 AI 時代需延伸。',limit:'目前網站只有原文，簡報、中英對照與頁碼證據仍待補。',tags:['SECI × GenAI','機器維度','文獻計量'],drive:'https://drive.google.com/drive/folders/1PQFaBeGvfhzLWL59bhE-NynoS-Rx3XOv',files:[['原文 PDF','A11/A11原文_Artificial_Knowledge_Generation_Cerchione2025.pdf']]},
  {id:'A09',stars:4,title:'RAG 企業知識管理系統評估',en:'RAG and LLMs for Enterprise Knowledge Management',role:'技術與方法',status:'已建研讀包',year:'2026',author:'Karakurt & Akbulut',method:'系統性文獻回顧／63 篇',verdict:'提供 RAG、檢索指標與真實部署缺口，是研究方法與技術路線的重要依據。',question:'企業 RAG 與 LLM 知識管理研究使用哪些架構、評估方法與指標？',theory:'RAG、語意向量檢索、企業知識管理。',findings:'研究多停留在實驗階段；密集向量檢索普遍，但真實部署與商業影響評估仍少。',use:'第三章實驗設計與評估指標；定位語意檢索和關鍵字搜尋的比較缺口。',limit:'系統性回顧的比例與數據引用，必須保留原文頁碼與表格位置。',tags:['RAG','語意向量','系統性回顧'],drive:'https://drive.google.com/drive/folders/1l8rCKJlF9Im7G_c26GYEXK1RoPlRsGjk',files:[['原文 PDF','A09/A09原文_RAG_and_LLMs_for_Enterprise_KM.pdf'],['中英對照','A09/A09中英對照.pdf'],['研讀簡報','A09/A09研讀簡報.pdf']]},
  {id:'A12',stars:3,title:'語意搜尋評估綜述',en:'Semantic Search Evaluation',role:'評估方法',status:'已建基本卡',year:'2024',author:'Zheng, Wang, Zhang, Kishore & Singh',method:'工業應用／預印本',verdict:'提供 on-topic rate 與離線評估流程，可轉化為檢索成效測量設計。',question:'如何用可自動化且可驗證的方式評估語意搜尋結果是否切題？',theory:'語意搜尋、資訊檢索、LLM 評估。',findings:'以黃金查詢集、Top-K 結果、LLM 判斷與人工驗證建立離線評估流程。',use:'第三章評估設計；建立答案切題率、要點評分與人工驗證規則。',limit:'屬預印本且未經同儕審查，引用時需明示並搭配期刊來源。',tags:['語意搜尋','on-topic rate','評估'],drive:'https://drive.google.com/drive/folders/1mBtGCOJHM1bFCJrcZJG7Ycpw0joT5VXw',files:[['原文 PDF','A12/A12原文_Semantic_Search_Evaluation_Zheng2024.pdf']]},

  {id:'A13',stars:5,title:'詞彙不匹配問題：人機溝通中的詞彙問題',en:'The Vocabulary Problem in Human-System Communication',role:'問題界定',status:'研讀包完成',year:'1987',author:'Furnas, Landauer, Gomez & Dumais',method:'行為實驗（五個應用領域）＋模擬',verdict:'本研究「為什麼找不到」的經典原典。把個人檢索困擾升級為有名字、有實證的四十年老問題。',question:'不同使用者為同一對象自發選用的詞彙，一致性有多高？只認單一關鍵字的系統會失敗多少？',theory:'詞彙問題（the vocabulary problem）、詞彙不匹配、無限別名（unlimited aliasing）。',findings:'任兩人採用相同詞彙的機率低於 0.20；只認單一指定詞的系統在常見情境下失敗率達八至九成；豐富的別名索引可使命中率提高三至五倍。',use:'第一章研究動機（證明非個人特例）；2.3 兩種檢索的機制差別；2.4 研究缺口（人工別名不可行→語意向量自動化→成效未經實證）；第三章同義改寫題設計依據。',limit:'1987 年研究，情境為命令列與早期檢索系統，不涉及語意向量技術；本篇只作問題界定與題型依據，不進入研究方法。同作者群 1990 年的 LSI 原典尚未調閱原文。',tags:['詞彙不匹配','資訊檢索','經典原典','研究缺口'],drive:'https://drive.google.com/drive/folders/1j9D5Zxg4-xkJviNo7Kktdkp9TigNBQQ6',files:[['文獻卡','A13/README.md'],['原文 PDF','A13/A13_original_Vocabulary_Problem_Furnas1987.pdf'],['中英對照 PDF','A13/A13_bilingual.pdf'],['中英對照 Word','A13/A13_bilingual.docx'],['研讀摘要 PDF','A13/A13_reading_summary.pdf'],['研讀摘要 Word','A13/A13_reading_summary.docx']]},

  {id:'A01',stars:3,title:'GenAI × SECI 隱性知識管理',role:'待整理文獻',status:'待建立網頁卡',tags:['GenAI','SECI','隱性知識'],drive:'https://drive.google.com/drive/folders/10iMMOprdSOPXTHcdwXaw9nM3z8PMEzEx'},
  {id:'A02',stars:2,title:'楊誼萱：知識助手',role:'待整理文獻',status:'待建立網頁卡',tags:['知識助手','碩論'],drive:'https://drive.google.com/drive/folders/11AClvbFUn8qTochk_1DS-7gNYYotbDt0'},
  {id:'A03',stars:1,title:'AI 整合導入專案 KM',role:'待整理文獻',status:'待建立網頁卡',tags:['AI 導入','KM'],drive:'https://drive.google.com/drive/folders/1UEcpI9tSCpqYZDzEeFJKTquLE1lBC8GT'},
  {id:'A07',stars:4,title:'NLP 隱性知識轉換 Tacit',role:'待整理文獻',status:'待建立網頁卡',tags:['NLP','隱性知識'],drive:'https://drive.google.com/drive/folders/17RjttANEFaYoxhFERqV6jZzHBqwxYjcJ'},
  {id:'B01',stars:2,title:'中小企業生成式 AI 知識管理',role:'中文實證',status:'待建立網頁卡',tags:['中小企業','GenAI','KM'],drive:'https://drive.google.com/drive/folders/1nbeCo8MiAGt-5fvS-0fpS07SFC-fmUXs'},
  {id:'B02',stars:2,title:'偏鄉 SECI 校本課程',role:'中文實證',status:'待建立網頁卡',tags:['偏鄉','SECI','課程'],drive:'https://drive.google.com/drive/folders/11LI1WuOeSlgLmMLztt9S70ZiWCoWdC85'},
  {id:'B03',stars:1,title:'食農知識創新',role:'中文參考',status:'待建立網頁卡',tags:['食農','知識創新'],drive:'https://drive.google.com/drive/folders/1UncHSfXtuZmS7SGnhC0P9KDAkZmDBzyu'},
  {id:'B04',stars:2,title:'生成式 AI 知識生產',role:'中文參考',status:'待建立網頁卡',tags:['GenAI','知識生產'],drive:'https://drive.google.com/drive/folders/11G1VWqzU06swSWOvEbrmNfC1kFP7eL9q'},
  {id:'D01',stars:1,title:'時間小偷／工作不安全感',role:'備查',status:'低優先備查',tags:['工作不安全感'],drive:'https://drive.google.com/drive/folders/1VKYssgKFHMBmaFiIH-FOa0T8nps8SS-m'},
  {id:'D04',stars:1,title:'中文學習者 ChatGPT 接受度',role:'備查',status:'低優先備查',tags:['ChatGPT','接受度'],drive:'https://drive.google.com/drive/folders/1ZknFPinnS6x_P8F-jZXscLYtMwF4hZzd'}
];

window.READING_PATH = ['A05','A04','A06','A08','A10','A11','A09','A12','A13'];
