T={
'30 60 90 Day Plan':'30-60-90天計畫','30 60 90 Days Plan':'30-60-90天計畫','3D':'3D立體','5 STEPS':'五步驟','5G':'5G通訊',
'AIDA':'AIDA行銷模型','AIDA Model':'AIDA行銷模型','Africa Map':'非洲地圖','Agenda':'議程','Agile':'敏捷開發','Agile Methodology':'敏捷開發方法',
'Agriculture':'農業','Alphabet':'英文字母','Anatomy':'人體解剖','Annual Report':'年度報告','Arrow':'箭頭','Artificial Intelligence':'人工智慧',
'Asia Map':'亞洲地圖','Aviation':'航空','Big Data':'大數據','Blue Ocean Strategy':'藍海策略','Brain':'大腦','Break Even Analysis':'損益平衡分析',
'Breast Cancer Day':'乳癌防治日','Bubble Map':'泡泡圖','Budget Forecasting':'預算預測','Budget':'預算','Business':'商業','Business Model Canvas':'商業模式圖',
'Business People':'商務人物','Business Plan':'營運計畫','Business Strategy':'經營策略','Buyer Persona':'買家人物誌','Calendar':'月曆',
'Challenges':'挑戰','Change Management':'變革管理','Chart':'圖表','Circle':'圓形','Cloud':'雲端','Communication':'溝通','Company Profile':'公司簡介',
'Comparison':'比較','Concentric Circles':'同心圓','Concentric Circles Diagrams':'同心圓圖','Construction':'營建工程','Coronavirus':'新冠病毒',
'Coronavirus and Social Distancing':'新冠病毒與社交距離','Cover':'封面','Credit Card':'信用卡','Cryptocurrency':'加密貨幣',
'Customer Journey':'顧客旅程','Customer Journey Map':'顧客旅程地圖','Customer Profile':'顧客輪廓','Cyber Security':'資訊安全','Cycle':'循環',
'Feedback':'回饋','Finance':'財務','Fishbone':'魚骨圖','Fitness':'健身','Flow Chart':'流程圖','Flow':'流程','Food':'美食','Framework':'框架',
'Funnel':'漏斗','Gantt':'甘特圖','Gantt Charts':'甘特圖','Gap Analysis':'差距分析','Geometric':'幾何','Goals':'目標','Governance':'治理',
'Growth':'成長','Harvey Ball':'哈維球','Health':'健康','Healthcare':'醫療照護','Hierarchy':'階層','Human Resources':'人力資源',
'IT Architecture':'IT架構','Iceberg':'冰山','Iceberg Diagram':'冰山圖','Innovation':'創新','Insurance':'保險','Introduction':'介紹',
'Investment':'投資','KPI':'KPI績效指標','KPI Dashboards':'KPI儀表板','Law':'法律','Leadership':'領導力','Loyalty Program':'會員忠誠計畫',
'Manufacturing':'製造業','Marketing':'行銷','Matrix':'矩陣','Matrix Diagram':'矩陣圖','Matrix Diagrams':'矩陣圖','McKinsey 7S Model':'麥肯錫7S模型',
'Medical':'醫療','Meeting':'會議','Mekko Chart':'馬賽克圖','Milestones':'里程碑','Mind Map':'心智圖','Mindmap':'心智圖','Mission':'使命',
'Mockup Devices':'裝置樣機','Money':'金錢','Network':'網絡','North America Map':'北美地圖','Numbers':'數字','Objective':'目標',
'Oceania Map':'大洋洲地圖','Office Scenes':'辦公室場景','Org Chart':'組織圖','PESTEL Analysis':'PESTEL總體環境分析','Performance':'績效',
'Pie Chart':'圓餅圖','Pillar':'支柱',"Porter's Five Forces":'波特五力',"Porter's Fove Forces":'波特五力','Pricing Table':'價目表','Pricing Tables':'價目表',
'Problem':'問題','Process':'流程步驟','Product Life Cycle':'產品生命週期','Product Roadmap':'產品路線圖','Profit and Loss':'損益表',
'Progress':'進度','Project Management':'專案管理','Project Proposal':'專案提案','Project Status':'專案狀態','Psychology':'心理學',
'Puzzle':'拼圖','Pyramid':'金字塔','TAM SAM SOM':'TAM-SAM-SOM市場規模','Table':'表格','Tables of Content':'目錄','Table of Content':'目錄',
'Target Market':'目標市場','Team':'團隊','Teamwork':'團隊合作','Technology':'科技','Thank You':'感謝頁','Time Management':'時間管理',
'Timeline':'時間軸','Title':'標題頁','Training':'教育訓練','Transportation and Logistics':'運輸物流','Travel':'旅遊','Tree Diagram':'樹狀圖',
'United States Map':'美國地圖','United States Maps':'美國地圖','Value Chain':'價值鏈','Venn':'文氏圖','Venn Diagram':'文氏圖','Veterinary':'獸醫',
'Vision':'願景','Watercolor':'水彩風','Waterfall Chart':'瀑布圖','Work From Home':'居家辦公','World Map':'世界地圖','Worldmap':'世界地圖',
}
